# generated by maixhub, tested on maixpy3 v0.4.8
# copy files to TF card and plug into board and power on
import sensor, image, lcd, time
import KPU as kpu
import gc, sys

from machine import UART,Timer                         #导入串口
from fpioa_manager import fm

fm.register(15 , fm.fpioa.UART1_RX, force=True)        #映射串口引脚
fm.register(16, fm.fpioa.UART1_TX, force=True)

uart = UART(UART.UART1, 9600, read_buf_len=4096)     #初始化串口6

input_size = (224, 224)
labels = ['8', '1', '2', '3', '4', '5', '6', '7']
anchors = [1.91, 2.41, 1.44, 2.22, 1.72, 2.16, 1.22, 2.0, 1.56, 1.88]

def lcd_show_except(e):
    import uio
    err_str = uio.StringIO()
    sys.print_exception(e, err_str)
    err_str = err_str.getvalue()
    img = image.Image(size=input_size)
    img.draw_string(0, 10, err_str, scale=1, color=(0xff,0x00,0x00))
    lcd.display(img)

def main(anchors, labels = None, model_addr="/sd/model-70945.kmodel", sensor_window=input_size, lcd_rotation=0, sensor_hmirror=False, sensor_vflip=False):
    sensor.reset()
    sensor.set_pixformat(sensor.RGB565)
    sensor.set_framesize(sensor.QVGA)
    sensor.set_windowing(sensor_window)
    sensor.set_hmirror(True)
    sensor.set_vflip(sensor_vflip)
    sensor.run(1)

    lcd.init(type=1)
    lcd.rotation(2)
    lcd.clear(lcd.WHITE)

    if not labels:
        with open('labels.txt','r') as f:
            exec(f.read())
    if not labels:
        print("no labels.txt")
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "no labels.txt", color=(255, 0, 0), scale=2)
        lcd.display(img)
        return 1
    try:
        img = image.Image("startup.jpg")
        lcd.display(img)
    except Exception:
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "loading model...", color=(255, 255, 255), scale=2)
        lcd.display(img)

    try:
        task = None
        task = kpu.load(model_addr)
        kpu.init_yolo2(task, 0.5, 0.3, 5, anchors) # threshold:[0,1], nms_value: [0, 1]
        while(True):
            img = sensor.snapshot()
            t = time.ticks_ms()
            objects = kpu.run_yolo2(task, img)
            t = time.ticks_ms() - t
            a = ''  # 如果没有识别到数字一，将a设为空字符串
            b = ''  # 如果没有识别到数字二，将b设为空字符串
            c = ''  # 如果没有识别到数字一，将a设为空字符串
            d = ''  # 如果没有识别到数字二，将b设为空字符串
            if objects:
                a1=0
                b1=0
                c1=0
                d1=0
                e1=0
                f1=0
                g1=0
                h1=0
                if objects:
                 detected_numbers = []  # 用于存储所有识别到的数字
            
            for obj in objects:
                pos = obj.rect()
                img.draw_rectangle(pos)
                img.draw_string(pos[0], pos[1], "%s : %.2f" %(labels[obj.classid()], obj.value()), scale=2, color=(255, 0, 0))
                A = labels[obj.classid()]
                detected_numbers.append(A)  # 将识别到的数字添加到列表中
                print(A)
            
            # 构造包含所有识别到数字的数据字符串
            if detected_numbers:
                # 方法1: 直接连接所有数字
                numbers_str = ''.join(detected_numbers)
                DATA = '@' + numbers_str + '@' + '@'
                
               
            else:
                DATA = '@@' + '@'  # 没有识别到任何数字
            
            uart.write(DATA)
            uart.write('\r\n')  # 发送换行符
            print("发送数据:", DATA)

        # 显示"Shu"字符在特定位置
            img.draw_string(5, 10, "Shu:", scale=1, color=(255, 0, 0))
            img.draw_string(5, 30, "Shu:", scale=1, color=(255, 0, 0))
            img.draw_string(5, 50, "Shu:", scale=1, color=(255, 0, 0))
            img.draw_string(5, 70, "Shu:", scale=1, color=(255, 0, 0))

        # 在特定位置显示识别到的数字
            img.draw_string(30, 10, a, scale=1, color=(255, 0, 0))
            img.draw_string(30, 30, b, scale=1, color=(255, 0, 0))                  #print(DATA)
            img.draw_string(30, 50, c, scale=1, color=(255, 0, 0))
            img.draw_string(30, 70, d, scale=1, color=(255, 0, 0))                  #print(DATA)
                    #img.draw_string(10, 200, "t:%dms" %(t), scale=2, color=(255, 0, 0))
                    #a = labels[obj.classid()]                # 假设 labels 是保存数字标签的列表
                    #b = obj.value()
                    #print("识别到的数字是：%s，可信度为：%.2f" % (a, b))
            #img.draw_string(50, 50, "ShuZi:%s" %(ShuZi), scale=2, color=(255, 0, 0))
            img.draw_string(10, 200, "t:%dms" %(t), scale=2, color=(255, 0, 0))
            lcd.display(img)
    except Exception as e:
        raise e
    finally:
        if not task is None:
            kpu.deinit(task)


if __name__ == "__main__":
    try:
        # main(anchors = anchors, labels=labels, model_addr=0x300000, lcd_rotation=0)
        main(anchors = anchors, labels=labels, model_addr="/sd/model-70945.kmodel")
    except Exception as e:
        sys.print_exception(e)
        lcd_show_except(e)
    finally:
        gc.collect()
